let constants = {
    DEFAULT_DB: 'eventopackage',
    MODELS: {
        admins: 'admins',
        executives: 'executives',
        subadmins: 'subadmins',
        superadmins: 'superadmins',
        organizers: 'organizers',
        users: 'users',
        events: 'events',
        eventreviews: "eventreviews",
        eventwishlists: "eventwishlists",
        services: 'services',
        items: 'items',
        equipments: 'equipments',
        categories: 'categories',
        discounts : 'discounts',
        ourproduct : 'ourproduct',
        notifications : 'notifications',
        promotionplans : 'promotionplans',
        customerimports : 'customerimports',
        settings : 'settings',
        notificationcoupons : 'notificationcoupons',
        eventbookingcoupons: 'eventbookingcoupons',
        eventbookings: 'eventbookings',
        getintouches : 'getintouches',
        entertainmentcomments : 'entertainmentcomments',
        fcointransactions : 'fcointransactions',
        fcoinintransactions: 'fcoinintransactions',
        agents : 'agents',
        fcoins : 'fcoins',
        promotionexistingusers : 'promotionexistingusers'
    }
};
module.exports = constants;
