let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listEntertainmentCtrl = require('../../controllers/organizer/entertainments/list');
const commentCtrl = require('../../controllers/organizer/entertainments/comment');
const mypostCtrl = require('../../controllers/organizer/entertainments/mypost');
router.get('/', helper.authenticateToken, listEntertainmentCtrl.withoutpagination);
router.post('/', helper.authenticateToken, listEntertainmentCtrl.withpagination);
router.post('/comment', helper.authenticateToken, commentCtrl.postcomment);
router.post('/allcomments', helper.authenticateToken, commentCtrl.allcomment);
router.get('/mypost', helper.authenticateToken, mypostCtrl.withoutpagination);
router.post('/mypost', helper.authenticateToken, mypostCtrl.withpagination);
module.exports = router;