var express = require('express');
var router = express.Router();
const helper = require('../../utilities/helper');
const fileHelper = require('../../utilities/multer.functions');
const listCtrl = require("../../controllers/organizer/promotions/list");
const saveCtrl = require("../../controllers/organizer/promotions/save");
const getOneCtrl = require("../../controllers/organizer/promotions/getone");
const selectusertypeCtrl = require("../../controllers/organizer/promotions/selectusertype");
const selectusersCtrl = require("../../controllers/organizer/promotions/selectusers");
const setscheduleCtrl = require("../../controllers/organizer/promotions/setschedule");
const importCtrl = require("../../controllers/organizer/promotions/import");
const userlistCtrl = require("../../controllers/organizer/promotions/userlist");
const checkalluserCtrl = require("../../controllers/organizer/promotions/checkallusers");
const checkuserCtrl = require("../../controllers/organizer/promotions/checkuser");
const settingCtrl = require("../../controllers/organizer/promotions/setting");
const paymentCtrl = require("../../controllers/organizer/promotions/payment");
const uploadBannerCtrl = require('../../controllers/organizer/promotions/uploadbanner');
router.post('/', helper.authenticateToken, listCtrl.list);
router.post('/save', helper.authenticateToken, saveCtrl.save);
router.post('/getone', helper.authenticateToken, getOneCtrl.getone);
router.post('/selectusertype', helper.authenticateToken, selectusertypeCtrl.selectusertype);
router.post('/selectusers', helper.authenticateToken, selectusersCtrl.selectusers);
router.post('/setschedule', helper.authenticateToken, setscheduleCtrl.setschedule);
router.post('/import', helper.authenticateToken, fileHelper.memoryUpload.single('file'), importCtrl.import);
router.post('/userlist', helper.authenticateToken, userlistCtrl.userlist);
router.post('/checkalluser', helper.authenticateToken, checkalluserCtrl.checkalluser);
router.post('/checkuser', helper.authenticateToken, checkuserCtrl.checkuser);
router.get('/setting', helper.authenticateToken, settingCtrl.getsettings);
router.post('/paynow', helper.authenticateToken, paymentCtrl.paynow);
router.post('/banner', helper.authenticateToken, fileHelper.memoryUpload.single('file'), uploadBannerCtrl.uploadbanner);
module.exports = router;