let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
let fileHelper = require('../../utilities/multer.functions');
const getsetProfileCtrl = require('../../controllers/organizer/profile/getsetprofile');
const setProfilePicCtrl = require('../../controllers/organizer/profile/setprofilepic');
const setBusinessProfileCtrl = require('../../controllers/organizer/profile/setbusinessprofile');
const setBusinessProfilePicCtrl = require('../../controllers/organizer/profile/setbusinessprofilepic');
router.get('/', helper.authenticateToken, getsetProfileCtrl.getprofile);
router.post('/', helper.authenticateToken, getsetProfileCtrl.setprofile);
router.post('/profilepic', helper.authenticateToken, fileHelper.memoryUpload.single('file'), setProfilePicCtrl.setprofilepic);
router.post('/businessprofile', helper.authenticateToken, setBusinessProfileCtrl.setbusinessprofile);
router.post('/businessprofilepic', helper.authenticateToken, fileHelper.memoryUpload.single('file'), setBusinessProfilePicCtrl.setbusinessprofilepic);
module.exports = router;
