var express = require('express');
var router = express.Router();
const helper = require('../../utilities/helper');
const fileHelper = require('../../utilities/multer.functions');
const listCtrl = require("../../controllers/organizer/promotions/list");
const saveCtrl = require("../../controllers/organizer/promotions/save");
const getOneCtrl = require("../../controllers/organizer/promotions/getone");
const uploadBannerCtrl = require('../../controllers/organizer/promotions/uploadbanner');
router.post('/', helper.authenticateToken, listCtrl.list);
router.post('/save', helper.authenticateToken, saveCtrl.save);
router.post('/getone', helper.authenticateToken, getOneCtrl.getone);
router.post('/banner', helper.authenticateToken, fileHelper.memoryUpload.single('file'), uploadBannerCtrl.uploadbanner);
module.exports = router;