let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const registerNewOrganizerCtrl = require('../../controllers/organizer/register/register');
const verifyotpOrganizerCtrl = require('../../controllers/organizer/register/verifyotp');
const forgotpasswordOrganizerCtrl = require('../../controllers/organizer/register/forgotpassword');
const changepasswordOrganizerCtrl = require('../../controllers/organizer/register/changepassword');
const resendotpOrganizerCtrl = require('../../controllers/organizer/register/resendotp');
const deleteOrganizerCtrl = require('../../controllers/organizer/register/deleteorganizer');
router.post('/', registerNewOrganizerCtrl.registerneworganizer);
router.post('/verifyotp', verifyotpOrganizerCtrl.verifyotpfororganizer);
router.post('/forgotpassword', forgotpasswordOrganizerCtrl.forgotorganizerpassword);
router.post('/changepassword', changepasswordOrganizerCtrl.changeorganizerpassword);
router.post('/resendotp', resendotpOrganizerCtrl.resendotpfororganizer);
router.post('/deleteorganizer', helper.authenticateToken, deleteOrganizerCtrl.deleteorganizerdata);
module.exports = router;
