let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
let fileHelper = require('../../utilities/multer.functions');
const getsetUserProfileCtrl = require('../../controllers/user/profile/getsetprofile');
const setUserProfilePicCtrl = require('../../controllers/user/profile/setprofilepic');
router.get('/', helper.authenticateToken, getsetUserProfileCtrl.getprofile);
router.post('/', helper.authenticateToken, getsetUserProfileCtrl.setprofile);
router.post('/profilepic', helper.authenticateToken, fileHelper.memoryUpload.single('file'), setUserProfilePicCtrl.profilepic);
module.exports = router;
