let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
let fileHelper = require('../../utilities/multer.functions');
const getsepAgentProfileCtrl = require('../../controllers/agent/profile/getsetprofile');
const sepAgentProfilePicCtrl = require('../../controllers/agent/profile/setprofilepic');
router.get('/', helper.authenticateToken, getsepAgentProfileCtrl.getprofile);
router.post('/', helper.authenticateToken, getsepAgentProfileCtrl.setprofile);
router.post('/profilepic', helper.authenticateToken, fileHelper.memoryUpload.single('file'), sepAgentProfilePicCtrl.setprofilepic);
module.exports = router;
