let express = require("express");
let router = express.Router();
const registerNewAgent = require('../../controllers/agent/register/register');
const verifyotpforAgentCtrl = require('../../controllers/agent/register/verifyotp');
const forgotpasswordforAgentCtrl = require('../../controllers/agent/register/forgotpassword');
const changeAgentpasswordCtrl = require('../../controllers/agent/register/changepassword');
const resendotpforAgentCtrl = require('../../controllers/agent/register/resendotp');
router.post('/', registerNewAgent.registernewagent);
router.post('/verifyotp', verifyotpforAgentCtrl.verifyotpforagent);
router.post('/forgotpassword', forgotpasswordforAgentCtrl.forgotagentpassword);
router.post('/changepassword', changeAgentpasswordCtrl.changeagentpassword);
router.post('/resendotp', resendotpforAgentCtrl.resendotpforagent);
module.exports = router;
